language: php

php:
  - 7.2

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction

script: phpunit

matrix:
  allow_failures:
    - php: 7.2
  fast_finish: true

notifications:
  on_success: never
  on_failure: always